6.2 Import
Import the data file you downloaded. Refer to Chapter 5 for importing data into R.

import <- read_csv("Data Files/tidyverse_example.csv")
It is always a good idea to get to know your dataframe before you start messing with it. What are the column names? What kind of values are stored in each column? How many observations are there? How many Subjects? How many Trials? etc.

What are the column names? use colnames() for a quick glance at the column names

colnames(import)
##  [1] "Subject"              "TrialProc"            "Trial"                "Condition"            "RT"                   "ACC"                 
##  [7] "Response"             "TargetArrowDirection" "SessionDate"          "SessionTime"
To take a quick look at the first few rows of a dataframe use head().

head(import)
## # A tibble: 6 x 10
##   Subject TrialProc Trial Condition      RT   ACC Response TargetArrowDirection SessionDate SessionTime
##     <dbl> <chr>     <dbl> <chr>       <dbl> <dbl> <chr>    <chr>                <chr>       <time>     
## 1   14000 practice      1 incongruent  1086     1 left     left                 08-30-2017  10:30:25   
## 2   14000 practice      2 incongruent   863     1 left     left                 08-30-2017  10:30:25   
## 3   14000 practice      3 congruent     488     1 right    right                08-30-2017  10:30:25   
## 4   14000 practice      4 incongruent   588     1 right    right                08-30-2017  10:30:25   
## 5   14000 practice      5 congruent     581     1 right    right                08-30-2017  10:30:25   
## 6   14000 practice      6 incongruent   544     1 right    right                08-30-2017  10:30:25
This gives you a good idea of what column names you will be working with and what kind of values they contain.

To evaluate what are all the unique values in a column you can use unique(). You can also use this in combination with length() to evaluate how many unique values are in a column.

unique(import$Condition)
## [1] "incongruent" "congruent"
unique(import$Trial)
##   [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
##  [36]  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
##  [71]  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105
## [106] 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140
## [141] 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175
## [176] 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192
max(import$Trial)
## [1] 192
length(unique(import$Subject))
## [1] 410
unique(import$TrialProc)
## [1] "practice" "real"
unique(import$ACC)
## [1] 1 0
All these functions we just used from colnames() to unique() were to temporarily evaluate our data. They are not required to perform the actual data analysis. Therefore, I usually just type these in the console. A general rule of thumb is that if it is not required to be saved in your Script file then just type it in the console.

Okay let’s take a look at how to use the dplyr functions to score this data.
