---
title: "R Workshop - Working with Dashbaords"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

Introduction
==================================
Column {.tabset}
--------------------

### Introduction 



<div style="margin-left: auto;
            margin-right: auto;
            width: 80%">
            
|  <b> <strong><u>Contents</u> </strong></b>       |   
|:------------------|
|   |    
| * <b> <strong><a href="actuarialexams.html">R for actuarial students</a>  -  CS1B and CS2B </strong></b>|        
| * <b> <strong><a href="distributions.html">Probability Distributions</a> </strong></b>|        
|   | 
</div>

Rsconnect
Shiny App
Deployment

--------------------------------

### Deplying Your Shiny App

* Account on ShinyApps.io
* {rsconnect} R package
* Log Files


Now deploying a shiny hap is very straightforward. The thing is that I just recommend

Going straight to this targeted, Miss immediately. 

Set yourself a target of a Deployable shiny app - and maintain it continuously
 
And one that you can update and revert to, I just continuously improve rather than having something stuck on your desktop ad infinitum, that you just put a periodically just essentially, there's a couple reasons it Does.

The hazard is that you actually start to get used to the difference in requirements for working on cloud - a different programming environment. 
Best to get used to this environment from the get-go.




---------------------------------------

