DMR Section 7 Character Manipulation

### Basics of Character Data (7.1)
The names of the fifty states are found in the data set state.name, which is embedded in R base installation.
nchar(state.name)

Displaying and concatenating Character strings (7.2)

paste(‘one’,2,’three’,4,’five’)


Working with Parts of Character Values (7.3)
The substring function can be used either to extract parts of character strings, or to change the values of parts of character strings.

Modifier Meaning
^              anchors expression to beginning of target
$              anchors expression to end of target
.               matches any single character except newline
|              separates alternative patterns
()             groups patterns together
*             matches 0 or more occurrences of preceding entity
?             matches 0 or 1 occurrences of preceding entity
+             matches 1 or more occurrences of preceding entity
{n}          matches exactly n occurrences of preceding entity
{n,}         matches at least n occurrences of preceding entity
{n,m}      matches between n and m occurrences


--------------------------------------------

### Substituting and Tagging (7.8)

R provides two functions sub() and gsub().
Each of these functions accepts a regular expression, a string containing what will be substituted for the regular expressions, and the string or strings to operate on.

<pre><code>
values =c('$11,317.35' , '$11,234.51', '$11,275.89',
          '$11,278.93', '$11,294.94')
</code></pre>

To use these values as numbers , the commas and dollar signs need to be removed before <tt>as.numeric()</tt> can be used.
values = c('75.99','(20.30)','55.20')


