{dblyr} {data-navmenu="R packages"}
==========================================

## DBI
The DBI package helps connecting R to database management systems (DBMS). DBI separates the connectivity to the DBMS into a “front-end” and a “back-end”. The package defines an interface that is implemented by DBI backends such as:

RPostgres,
RMariaDB,
RSQLite,
odbc,
bigrquery,
and many more, see the list of backends. R scripts and packages use DBI to access various databases through their DBI backends.

The interface defines a small set of classes and methods similar in spirit to Perl’s DBI, Java’s JDBC, Python’s DB-API, and Microsoft’s ODBC. It supports the following operations:

* connect/disconnect to the DBMS
* create and execute statements in the DBMS
* extract results/output from statements
* error/exception handling
* information (meta-data) from database objects
* transaction management (optional)

#### Installation
Most users who want to access a database do not need to install DBI directly. It will be installed automatically when you install one of the database backends:

* RPostgres for PostgreSQL,
* RMariaDB for MariaDB or MySQL,
* RSQLite for SQLite,
* odbc for databases that you can access via ODBC,
* bigrquery,
* … .


You can install the released version of DBI from CRAN with:

<pre><code>
install.packages("DBI")
</code></pre>

-----------------------------------------------------------

## Using {DBI}

### Connection

<pre><code>
> con
<OdbcConnection> MY_COMPANY\MY_NAME@THISDB
  Database: MY_DB_NAME
  Microsoft SQL Server Version: 14.00.3451
>
> class(con)
[1] "Microsoft SQL Server"
attr(,"package")
[1] ".GlobalEnv"

</code></pre>


### <tt>dbListTables()</tt>

* dbListTables() returns a character vector that enumerates all tables and views in the database. 
* Tables added with dbWriteTable() are part of the list. 
* As soon a table is removed from the database, it is also removed from the list of database tables.

<pre><code>
dbListTables(con)
</code><pre>

### <tt>dbColumnInfo()</tt>

<pre><code>
dbColumnInfo(dbSendQuery(con, "SELECT * from tblProductionStems"))
</code></pre>
