{dblyr} {data-navmenu="Workshop"}
==========================================

Column {.tabset}
--------------------

### {dblyr} 

this R package allows the user to Create an SQL query.

By interpreting a Conventional piece of a rcode.
This queryThat would be then passed to the database As standard SQL.

The results of this query can then be collected by our and retrieved into the our environment for further processing.

This is very useful because it allows Data analysis Without downloading the entire contents of the database.

We are mindful that The data can bE Many millions of rows.

I basically not possible to download into the R environment at all.

This approach is very convenient and very cost efficient in terms of memoryAnd computational time.

The overall structure of the package is very simple If you are already familiar with tidy verse,


#### Level of Sophistication of the SQL Query

I recommend a straightforward SQL query - with minimal complications - that contains "enough" information
Once the Query is collected into the R environment, further elaborations can be carried out



#### DBA knowledge

The most complex part of This approach is actually creating the Database connection.

What is required here is knowledge of the Database permissions 

In a corporate setting, It is best to contact. The DBA connection string will have the following sort of formats. 
<pre><code>
CODE
</code></pre>

These permissions are commercially sensitive and must be kept secure and secret for cyber-security purposes.

### Northwind

https://en.wikiversity.org/wiki/Database_Examples/Northwind

About the Northwind sample database
The Northwind database is a sample database that was originally created by Microsoft and used as the basis for their tutorials in a variety of database products for decades. The Northwind database contains the sales data for a fictitious company called “Northwind Traders,” which imports and exports specialty foods from around the world. The Northwind database is an excellent tutorial schema for a small-business ERP, with customers, orders, inventory, purchasing, suppliers, shipping, employees, and single-entry accounting. The Northwind database has since been ported to a variety of non-Microsoft databases, including PostgreSQL.

The Northwind dataset includes sample data for the following.

Suppliers: Suppliers and vendors of Northwind
Customers: Customers who buy products from Northwind
Employees: Employee details of Northwind traders
Products: Product information
Shippers: The details of the shippers who ship the products from the traders to the end-customers
Orders and Order_Details: Sales Order transactions taking place between the customers & the company
The Northwind sample database includes 14 tables and the table relationships are showcased in the following entity relationship diagram.

https://stackoverflow.com/questions/58458761/where-can-i-download-the-northwind-sample-database-for-sqlite
