
   <h3>Installed Data sets</h3>

* To assist in the demonstration of statistical approaches and tests, there are several dozen embedded data sets that come 
pre-installed with R.  
* To view the list of such data sets currently available, type in <code>data()</code> to the command line.

<p>One data set we will be using frequently is the <b><i>iris</i><b> data set.

  (To view the column names, and the first six cases, we will use the command <code>head()</code>. 
  To view the last six cases, use the command <code>tail()</code> ).
<pre><code>
data()

iris

head(iris)
</code></pre>
While we will be covering very little material relevant to graphics, it is worth nothing how many colours are supported by R.  To get a full list of currently supported colours, type in the command colours().


### 1.10 Built-In Data Sets

 Several data sets , intended as learning tools, are automatically installed when R is installed.
 Many more are installed within packages to complement learning to use those packages. 
 bigskip
 
 textbf{iris} One
 of these is the famous Iris data set, which is used in many data mining exercises.
 
 
*  airquality  ( very useful )
*  mtcars
*  Nile
 
 More are available once packages are loaded.
 
 
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Rdatasets}
 end{figure}

 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/RdatasetsMore}   
 end{figure}

 
*  To see what data sets are available, simply type texttt{data()}.
*  To load a data set, simply type in the name of the data set. Some data sets are very large.
 *  To just see the first few (or last) rows, we
 use the texttt{head()} function or alternatively the texttt{tail()} function. 
*  The default number of rows of
 these commands is 6. Other numbers can be specified.

 
*  In many situations, it is useful to call a particular data set using the texttt{attach()} command. This
 will save having to specify the data sets over repeated operations. 
*  The file can then be detached
 using the texttt{detach()} command.
 
 
 
 
 %==============================================================================================%
 
### {2.3 Colours}
 
*  R supported a massive number of colours.
*  Type in colours() (or colors()) to see what colours
 are supported.
 
 
 
 
