---
title: "R Workshop - Working With Text"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

Introduction
==================================
Column {.tabset}
--------------------

### Introduction 



<div style="margin-left: auto;
            margin-right: auto;
            width: 80%">
            
|  <b> <strong><u>Contents</u> </strong></b>       |   
|:------------------|
|   |    
| * <b> <strong><a href="actuarialexams.html">R for actuarial students</a>  -  CS1B and CS2B </strong></b>|        
| * <b> <strong><a href="distributions.html">Probability Distributions</a> </strong></b>|        
|   | 
</div>


### Data Sets



#### cheddar: Taste of Cheddar cheese


* <tt>grep()</tt> and <tt>grepl()</tt>
* <tt>gsub()</tt>
* <tt>nchar()</tt>

------------------------------

<pre><code>
nchar()
</code></pre>

--------------------

<pre><code>
gsub("old","new",myText)
</code></pre>

---------------------------------------


### `sprintf()`

```{r}


## various formats of pi :

sprintf("%f", pi)
sprintf("%.3f", pi)
sprintf("%1.0f", pi)
sprintf("%5.1f", pi)
sprintf("%05.1f", pi)
sprintf("%+f", pi)
sprintf("% f", pi)
sprintf("%-10f", pi) # left justified
sprintf("%e", pi)
sprintf("%E", pi)
sprintf("%g", pi)
sprintf("%g",   1e6 * pi)    # -> exponential
sprintf("%.9g", 1e6 * pi)    # -> "fixed"
sprintf("%G", 1e-6 * pi)

```

### The ``rep() `` command

```{r}
rep( "WH", 10)
rep( c("WH","LD"), 5)
rep( c("WH","LD"), times = 5)
rep( c("WH","LD"), each = 5)
rep( c("WH","LD"), each = 2, times = 3)
rep( c("WH","LD"), times=c(3,7) ) 
```

### The `paste()` command

```{r}

part1 <- rep( c("WH","LD"),5)
part2 <- sprintf("%02.0f", 1:10)

paste(part1,part2)
paste(part1,part2,sep="-") # hyphen seperator
paste(part1,part2,sep="")  # no white space, i.e. no gap
```
