Pareto (Type I) Distribution {data-navmenu="Continuous Distributions"}
==============================================================

Column {.tabset}
--------------------------------

### Pareto Distribution

<h4>Defintions</h4>

#### Cumulative distribution function
From the definition, the cumulative distribution function of a Pareto random variable with parameters $\alpha$ and $x_{\mathrm {m}$ is

$${\displaystyle F_{X}(x)={\begin{cases}1-\left({\frac {x_{\mathrm {m} }}{x}}\right)^{\alpha }&x\geq x_{\mathrm {m} },\\0&x<x_{\mathrm {m} }.\end{cases}}}
$$
\end{cases}

#### Probability density function

It follows (by differentiation) that the probability density function is

$${\displaystyle f_{X}(x)={\begin{cases}{\frac {\alpha x_{\mathrm {m} }^{\alpha }}{x^{\alpha +1}}}&x\geq x_{\mathrm {m} },\\0&x<x_{\mathrm {m} }.\end{cases}}}$$
 

### Pareto Distribution - Worked Examples

<h4> Worked Example 1</h4>

The claim severity for an auto liability insurance coverage is modeled by a Pareto Type I distribution with shape parameter $\alpha=2.5$ and scale parameter $\theta=1000$. 
The insurance coverage pays up to a limit of 1200 per claim. 

Using a seed of 1234, simulate the nominal value of 50,000 such insurance claims.
Estimate the expected insurance payment under this coverage for one claim.

<a href = "https://youtu.be/HYI881qtKVA"> Click Here for Video</a>