---
title: "R Workshop"
author: "dragonflystats"
#date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output: rmdformats::readthedown
editor: source
execute:
  message: false
  warning: false
  error: false
format:
  html:
    theme:
      light: sandstone
      dark: darkly
    anchor-sections: true
    embed-resources: true
    number-sections: true
    smooth-scroll: true
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-summary: "Show code"
    fig-width: 11
    fig-height: 8
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
```

Introduction
==================================
Column {.tabset}
--------------------

### Introduction 



<div style="margin-left: auto;
            margin-right: auto;
            width: 80%">
            
|  <b> <strong><u>Contents</u> </strong></b>       |   
|:------------------|
|   |    
| * <b> <strong><a href="actuarialexams.html">R for actuarial students</a>  -  CS1B and CS2B </strong></b>|        
| * <b> <strong><a href="distributions.html">Probability Distributions</a> </strong></b>|        
|   | 
</div>


### Data Sets



#### cheddar: Taste of Cheddar cheese

In **{faraway}**: Functions and Datasets for Books by Julian Faraway

#### Description
In a study of cheddar cheese from the LaTrobe Valley of Victoria, Australia, samples of cheese were analyzed for their chemical composition and were subjected to taste tests. Overall taste scores were obtained by combining the scores from several tasters.


* **taste** - a subjective taste score

* **Acetic** - concentration of acetic acid (log scale)

* **H2S** - concentration of hydrogen sulfice (log scale)

* **Lactic** - concentration of lactic acid

---------------------------------------

<pre><code>

Str2expreas eval
Rm
Ls
Rm(list=ls())


Objects and object classes.
Object sizes.
</code></pre>
-------------------------------------------

```{r child= "Segments/String_Evaluation.Rmd"}
```


Chapter Name
======================

## Section 1

### Test


#### Subtest

### Definitions

Chapter 2 Name
======================

## Section A

### Test

### System Content 1

#### Subtest

### Content 2

Chapter 3 Name
======================

## Section B

## Section C Test


#### Subtest
